#version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: devops_mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: devops_mongo_express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  backend:
    build: ./backend
    container_name: devops_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      # Volume for uploaded resumes
      - ./backend/uploads:/usr/src/app/uploads
      # Volume for frontend static files
      - ./backend/public:/usr/src/app/public

volumes:
  mongo_data:

